# Usar OpenJDK 17
FROM openjdk:17-jdk-slim

# Criar diretório da aplicação
WORKDIR /app

# Copiar o projeto inteiro
COPY . .

# Instalar Maven e construir o projeto
RUN apt-get update && apt-get install -y maven && mvn clean package -DskipTests

# Copiar o JAR gerado para rodar no container
COPY target/api-0.0.1-SNAPSHOT.jar app.jar

# Expor porta 8080
EXPOSE 8080

# Comando para rodar a aplicação
CMD ["java", "-jar", "app.jar"]
